version: '3.8'

services:
  pagamento-service:
    build:
      context: .
    container_name: pagamento-service
    ports:
      - "8085:8085"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - default

  postgres:
    image: postgres:15
    container_name: postgres-pagamento
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pagamento_db
    volumes:
      - postgres_data_pagamento:/var/lib/postgresql/data
    ports:
      - "5435:5432"  # Evita conflito com outros serviços usando 5432
    networks:
      - default

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"  # UI do RabbitMQ
    networks:
      - default


volumes:
  postgres_data_pagamento:
